In [2]:
import numpy as np

# attributes 

a = np.array([1,2,3])    # 1D array

In [6]:
print(a)

[1 2 3]


In [15]:
print (a.ndim)
print (a.shape)
print(a.dtype)
print(a.itemsize)

1
(3,)
int32
4


In [14]:
td = np.array([[1,2,3],[4,5,6]])    # 2D array
td
print(td.ndim)
print(td.shape)            # no of rows and column in an array
print(td.dtype)

2
(2, 3)
int32


In [16]:
td = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])   #  3D array
td
print(td.ndim)
print(td.shape)            # no of rows and column in an array
print(td.dtype)

3
(2, 2, 3)
int32


In [17]:
# create 2 matrix , take transpose and take addition 
matrix1 = np.array([[1,2,3],[4,5,6]])
matrix2 = np.array([[11,12,13],[14,15,16]])

In [21]:
print (matrix1)
print (matrix1.shape)
print (matrix2)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[11 12 13]
 [14 15 16]]


In [20]:
print (matrix1.T)
print (matrix1.T.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [22]:
print(matrix1)

[[1 2 3]
 [4 5 6]]


In [23]:
addm3 = matrix1 + matrix2
print(addm3)

[[12 14 16]
 [18 20 22]]


In [24]:
multiplym4 = matrix1 * matrix2
print(multiplym4)

[[11 24 39]
 [56 75 96]]


In [26]:
tda = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]],[[10,20,30],[40,50,60]]])
tda

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [47]:
tbta = np.array([[1,2,3],[4,5,6],[7,8,]])
tbta

array([list([1, 2, 3]), list([4, 5, 6]), list([7, 8])], dtype=object)

In [36]:
print (np.mean(tbta,axis=0))
tbta.mean()     # default mean gives avg of all values 

[4. 5. 6.]


5.0

In [29]:
tbta.mean(axis=1) # finds the mean of each rows

array([2., 5., 8.])

In [30]:
tbta.mean(axis=0)   # finds the mean of each cols

array([4., 5., 6.])

In [35]:
#  here we are using all maths formula for list 

print("std col wise",tbta.std(axis=0))   # std col wise
print("variance",tbta.var(axis=0))   # variance
print("max of each column",tbta.max(axis=0))   # max of each column
print("min of each column",tbta.min(axis=0))   # min of each column
print("sum of each column",tbta.sum(axis=0))   # sum of each column
print("prod of each column",tbta.prod(axis=0))   # prod of each column


std col wise [2.44948974 2.44948974 2.44948974]
variance [6. 6. 6.]
max of each column [7 8 9]
min of each column [1 2 3]
sum of each column [12 15 18]
prod of each column [ 28  80 162]


In [39]:
#  here we are using all maths formula for numpy 

print("std col wise",np.std(tbta,axis=0))   # std col wise
print("variance",np.var(tbta,axis=0))   # variance
print("max of each column",np.max(tbta,axis=0))   # max of each column
print("min of each column",np.min(tbta,axis=0))   # min of each column
print("sum of each column",np.sum(tbta,axis=0))  # sum of each column
print("prod of each column",np.prod(tbta,axis=0))   # prod of each column


std col wise [2.44948974 2.44948974 2.44948974]
variance [6. 6. 6.]
max of each column [7 8 9]
min of each column [1 2 3]
sum of each column [12 15 18]
prod of each column [ 28  80 162]


In [53]:
tbta = np.array([[1,2,0],[4,5,0],[7,8,0]])
np.any(tbta,axis=0)                        #   if column has all 0 values then it will return false 

tbta = np.array([[1,2,6],[4,5,5],[7,8,0]])
np.all(tbta,axis=0)


array([ True,  True, False])

In [55]:
####   Slicing 
# Array Indexing and slicing

In [65]:
arr = [1,2,3,4,5,6]
print(arr)
print(arr[0],arr[1],arr[2])   # access elem of 1D array
print(arr[1:-1])              
print(arr[:])                 # Print entire array
print(arr[1:])
print(arr[:5])
arr[1] =7                    # Update array
print(arr)

[1, 2, 3, 4, 5, 6]
1 2 3
[2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
[2, 3, 4, 5, 6]
[1, 2, 3, 4, 5]
[1, 7, 3, 4, 5, 6]


In [66]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(arr[0],arr[1],arr[2])   # access elem of 1D array
print(arr[1:-1])              
print(arr[:])                 # Print entire array
print(arr[1:])
print(arr[:5])
arr[1] =7                    # Update array
print(arr)

[1 2 3 4 5 6]
1 2 3
[2 3 4 5]
[1 2 3 4 5 6]
[2 3 4 5 6]
[1 2 3 4 5]
[1 7 3 4 5 6]


In [86]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,0],[16,17,18,19,10]])
print(arr)
print(arr[0][0],arr[0][1],arr[1][2])   # access elem of 1D array
print(arr[1:2,2:4])  
print(arr[1:2],arr[2:4]) 
print(arr[:,0:2]) 
#print(arr[:])                 # Print entire array
#print(arr[1:])
#print(arr[:5])
#arr[1] =7                    # Update array
#print(arr)
print(arr[:,0:2]) 
print(arr[0:2,:])

[[ 1  2  3  4  5]
 [ 6  7  8  9  0]
 [16 17 18 19 10]]
1 2 8
[[8 9]]
[[6 7 8 9 0]] [[16 17 18 19 10]]
[[ 1  2]
 [ 6  7]
 [16 17]]
[[ 1  2]
 [ 6  7]
 [16 17]]
[[1 2 3 4 5]
 [6 7 8 9 0]]


In [87]:
print(arr[:,0:2]) 
print(arr[0:2,:])

[[ 1  2]
 [ 6  7]
 [16 17]]
[[1 2 3 4 5]
 [6 7 8 9 0]]


In [ ]:
# create array using list 


In [88]:
# create array using arange 
arr = np.arange(10,100)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [91]:
zero_arr = np.zeros((5,5))
print(zero_arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [93]:
one_arr = np.ones((5,5))
print(one_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [100]:
full_array = np.full((5,5),0)
full_array

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [101]:
arr4 = np.arange(10).reshape(2,5)
arr4

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [102]:
# linespace

In [104]:
# random value 
np.random.random((3,3))

array([[0.63603095, 0.54216599, 0.35356801],
       [0.11554219, 0.25747201, 0.12717182],
       [0.29027923, 0.15978466, 0.73925722]])

In [106]:
np.random.randint(0,10,(3,3))

array([[7, 5, 1],
       [9, 9, 2],
       [7, 9, 6]])

In [4]:
# create Identity matrix
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
arr = np.empty([3,2],dtype=int)
arr

array([[         0, 1072693248],
       [         0, 1072693248],
       [         0, 1072693248]])