In [1]:
import numpy as np
import pandas as pd

In [5]:
print (pd.__version__)
pd?

0.25.1


In [19]:
series = pd.Series([10,20,30,40,50])
print (series)
print (series.index)
print (series.values)
print (type(series))
print (type(series.values))
print (series.values.dtype)

0    10
1    20
2    30
3    40
4    50
dtype: int64
RangeIndex(start=0, stop=5, step=1)
[10 20 30 40 50]
<class 'pandas.core.series.Series'>
<class 'numpy.ndarray'>
int64


In [25]:
index = ['a','b','c','d','e']
series = pd.Series([10,20,30,40,50],index=index)
print (series)
print (series.index)
print (series.values)

a    10
b    20
c    30
d    40
e    50
dtype: int64
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[10 20 30 40 50]


In [28]:
arr = np.array([10,20,30,40,50])
series = pd.Series(arr,index=index)     #  np creates arr with less memory see int32 
print (series)
print (series.index)
print (series.values)

a    10
b    20
c    30
d    40
e    50
dtype: int32
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[10 20 30 40 50]


In [32]:
# creating series with dictionry 

dict = {'a':10,'b':20,'c':30,'d':40}
series = pd.Series(dict)
print (series)
print (series.index)
print (series.values)

print ('b' in dict)

a    10
b    20
c    30
d    40
dtype: int64
Index(['a', 'b', 'c', 'd'], dtype='object')
[10 20 30 40]
True


In [39]:
# Indexing and slicing 
arr = np.array([89,78,67,56,45]);
index1= [5,6,7,8,9]
series= pd.Series(arr,index=index1)
print(series)

5    89
6    78
7    67
8    56
9    45
dtype: int32


In [37]:
arr = np.array([89,78,67,56,45]);
print (arr[3])
print (arr[1:4])
print (arr[:4])
print (arr[1:4:2])

56
[78 67 56]
[89 78 67 56]
[78 56]


In [43]:
ser_list = pd.Series([10.1,20.1,30.3,40.4,50.2])
print(ser_list)
fancy_series = pd.Series(ser_list,[3,2])
print(fancy_series)

0    10.1
1    20.1
2    30.3
3    40.4
4    50.2
dtype: float64
3    40.4
2    30.3
dtype: float64


In [49]:
ser_using_dict = pd.Series(dict)
print (ser_using_dict)
print ('\n')
print (ser_using_dict['a'])

a    10
b    20
c    30
d    40
dtype: int64


10


In [58]:
dict = {'a':10,'b':20,'c':30,'d':40}
series = pd.Series(dict)
print (series['a':'b'])

a    10
b    20
dtype: int64


In [59]:
#Accessing series elements in a dictionary way. this is with explicit index or key
dict = {'a':10, 'b':20, 'c':30, 'd':40, 'e':50}      #creating a Dictionary
print("dictionary is ", dict)
ser_dict = pd.Series(dict)         # creating a Series from a Dictionary
#print(ser_dict.index)
#print(ser_dict['a'])
#print(ser_dict['a':'c'])       # [1:4]
#print("ser_dict[: 'd']:\n", ser_dict[:'d'])
#print("ser_dict[['b', 'e']]:\n",  ser_dict[['b', 'e']])    #Fancy Indexing 
print(ser_dict[1:3])    #with explicit index default index also exists


dictionary is  {'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}
b    20
c    30
dtype: int64


In [62]:
#Problem that may arise with implicit and explicit indexing
#Consider an Example where the explicit index is also a number
s = pd.Series([5,4,3,2],  index=[100, 200, 300,400])  # index has to be given as 2nd parameter
print("Series is : \n", s, '\n Indices are : ', s.index) 
print(s[100:300])     #100 and 300 not the default index
#print(s[1:3])


Series is : 
 100    5
200    4
300    3
400    2
dtype: int64 
 Indices are :  Int64Index([100, 200, 300, 400], dtype='int64')
Series([], dtype: int64)


In [66]:
#the loc() - indexing and slicing with explicit index
#the iloc() - indexing and slicing with implicit index
s = pd.Series([5,4,3,2],  index=[100, 200, 300,400])  # index has to be given as 2nd parameter
print("Series is : \n", s, '\n Indices are : ', s.index)
print("Series with explicit index :s.loc[100:300]\n", s.loc[100:300])  #it will take the end value too
#print("Series with implicit index:  s.iloc[1:3] \n" , s.iloc[1:3])
print('Implicit access  : s.iloc[2] \n' , s.iloc[2])
print('Explicit access  : s.loc[200] \n' , s.loc[200])


Series is : 
 100    5
200    4
300    3
400    2
dtype: int64 
 Indices are :  Int64Index([100, 200, 300, 400], dtype='int64')
Series with explicit index :s.loc[100:300]
 100    5
200    4
300    3
dtype: int64
Implicit access  : s.iloc[2] 
 3
Explicit access  : s.loc[200] 
 4


In [67]:
# loc - explicit index will take indexing from start to stop 
# iloc - implicit index will take indexing from start to stop-1

#Difference between Implit and Explicit Indexing

### Explicit index use loc[] series.loc[slice] slice will take start to stop
### Implict index use iloc[] series.iloc[slice] slice will take start to stop-1
