In [1]:
l = [1, 2, 3]
l

[1, 2, 3]

In [3]:
list_compre = [i for i in range(5)]
list_compre

[0, 1, 2, 3, 4]

In [5]:
nested_list = [[i for i in range(5)] for j in range(5)]
nested_list

[[0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4]]

In [15]:
t = []
t.append(1)
#t.append([1,2,3])
t.extend((1,2,3))
t

[1, 1, 2, 3]

In [9]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [41]:
import time

l1 = range(1000)
l2 = range(1000)
start = time.time()
result = [(x+y) for x , y in zip(l1, l2)]
print("Execution Time For python list :" , (time.time() - start) * 1000)

Execution Time For python list : 0.9982585906982422


In [21]:
for i,num in enumerate(l1):
    print (i,num)

0 1
1 2
2 3
3 4


In [20]:
a1 = np.arange(1000)
a2 = np.arange(1000)

import time
start = time.time()
a3 = a1 + a2
print ("Execution time: - ", time.time() - start * 1000)

Execution time: -  -1606219063191.5054


In [26]:
a1 = np.array([[1,2,3],[2,3]])
a1

array([list([1, 2, 3]), list([2, 3])], dtype=object)

In [28]:
a2 = np.array([[1,2,3],[1,2,3],[1,2,3]])
a2

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [30]:
a3 = np.array([[1,2,3],[1,2,3],[1,2,'a']])
a3

array([['1', '2', '3'],
       ['1', '2', '3'],
       ['1', '2', 'a']], dtype='<U11')

In [38]:
import sys
a4 = np.array([[1,2,3],[1,2,3]])
print (sys.getsizeof(a4))

a5 = [[1,2,3],[1,2,3]]
print (sys.getsizeof(a5))

136
80


In [42]:
numpy_array = np.array([[1,3], [3,4], [5,6]])
print("\n A numpy array: \n" , numpy_array)
print("\n Type : ", type(numpy_array))
print("\n Dtype : " , numpy_array.dtype)
print("\n NDim : " , numpy_array.ndim) # Dimensions of numpy array
print("\n ItemSize : " , numpy_array.itemsize) # size of a single element in the numpy array
'''Shape of numpy array in (rows,columns)the shape of an array is a tuple of integers giving the size of the array along each dimension.'''
print("\n Shape : " , numpy_array.shape)
print("\n NBytes : " , numpy_array.nbytes)


 A numpy array: 
 [[1 3]
 [3 4]
 [5 6]]

 Type :  <class 'numpy.ndarray'>

 Dtype :  int32

 NDim :  2

 ItemSize :  4

 Shape :  (3, 2)

 NBytes :  24


In [43]:
#Typecasting of numpy arrays
arr_fl = np.array([[1,2], [3,4], [5,6]] , dtype = np.float64)
print(" A Float Array: \n" , arr_fl)
arr_comp = np.array([[1,2], [3,4], [5,6]] , dtype = np.complex)
print(" A Complex Array: \n" , arr_comp)


 A Float Array: 
 [[1. 2.]
 [3. 4.]
 [5. 6.]]
 A Complex Array: 
 [[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]


In [44]:
# Initialize all the elements of the numpy array with 0
zero_array = np.zeros((5,5),dtype=int)
print(zero_array)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [47]:
# Initialize all the elements of the numpy array with 0
zero_array = np.ones((5,5))
print(zero_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [48]:
#Array filled with
full_array = np.full((4,3), 2.5)
print(full_array)

[[2.5 2.5 2.5]
 [2.5 2.5 2.5]
 [2.5 2.5 2.5]
 [2.5 2.5 2.5]]
