In [3]:
# 3.Aritmetic Functions

import pandas as pd

#Create two series
s1=pd.Series([6,7,8,9,5])
s2=pd.Series([0,1,2,3,4,5,7])
print('Series are : \n',s1, '\n', s2)

Series are : 
 0    6
1    7
2    8
3    9
4    5
dtype: int64 
 0    0
1    1
2    2
3    3
4    4
5    5
6    7
dtype: int64


In [4]:
#Series with char/ string elements
string=pd.Series(['a','b','c','S','e','J','g','B','P','o'])
print('A Series wih String values: \n ', string)
print('string.str.upper(): \n',string.str.upper())
print('string.str.lower(): \n',string.str.lower())


A Series wih String values: 
  0    a
1    b
2    c
3    S
4    e
5    J
6    g
7    B
8    P
9    o
dtype: object
string.str.upper(): 
 0    A
1    B
2    C
3    S
4    E
5    J
6    G
7    B
8    P
9    O
dtype: object
string.str.lower(): 
 0    a
1    b
2    c
3    s
4    e
5    j
6    g
7    b
8    p
9    o
dtype: object


In [6]:
#6.Pandas DataFrames
#Creation of DataFrames
#Dataframe as a stack of Series. we create two columns using series and then make a DataFrame

population_d= {'California': 3833, 'Texas': 8193, 'New York': 6511, 'Florida': 5560, 'Ohio': 1135} #Statewise population

#print(population_d, type(population_d))
population = pd.Series(population_d)
print(population)


California    3833
Texas         8193
New York      6511
Florida       5560
Ohio          1135
dtype: int64


In [8]:
area_d = {'California': 423967, 'Texas': 695662, 'New York': 141297,  'Florida': 170312, 'Ohio': 149995}
area = pd.Series(area_d)
print(area)


California    423967
Texas         695662
New York      141297
Florida       170312
Ohio          149995
dtype: int64


In [9]:
states = pd.DataFrame({'Population': population, 'Area': area}) #two series with same index
print("Data Frame of States: \n", states)

Data Frame of States: 
             Population    Area
California        3833  423967
Texas             8193  695662
New York          6511  141297
Florida           5560  170312
Ohio              1135  149995


In [12]:
# create dict with Numpy array 

import numpy as np
num_arr=np.random.randn(6,4) #random delection of numbers following a standard normal distribution

print("Array is : \n", num_arr)
cols=['A','B','C','D'] #arrays will not have index and columns
df1=pd.DataFrame(num_arr, columns=cols, index = ['i', 'ii', 'iii', 'iv', 'v', 'vi'])

#array of values, index, column
print('\n Data Frame from numpy array is : \n')
print(df1)

df1

Array is : 
 [[-0.24878389  0.0082247   1.81506879  0.82785869]
 [-0.24320366 -0.31404347 -0.18200454 -0.25730413]
 [ 0.07553616  0.842246    0.00909922  1.02356254]
 [-1.11050775  0.89796613 -0.03985498 -0.10499166]
 [-1.20616971  0.47509261  0.4587711   1.87065952]
 [-0.31586353 -1.42527405 -0.1119677  -1.65189778]]

 Data Frame from numpy array is : 

            A         B         C         D
i   -0.248784  0.008225  1.815069  0.827859
ii  -0.243204 -0.314043 -0.182005 -0.257304
iii  0.075536  0.842246  0.009099  1.023563
iv  -1.110508  0.897966 -0.039855 -0.104992
v   -1.206170  0.475093  0.458771  1.870660
vi  -0.315864 -1.425274 -0.111968 -1.651898


A         B         C         D
i   -0.248784  0.008225  1.815069  0.827859
ii  -0.243204 -0.314043 -0.182005 -0.257304
iii  0.075536  0.842246  0.009099  1.023563
iv  -1.110508  0.897966 -0.039855 -0.104992
v   -1.206170  0.475093  0.458771  1.870660
vi  -0.315864 -1.425274 -0.111968 -1.651898

In [13]:
# create a dataframe using a dictionary of Lists, values are lists and column names are keys

data= {'city' : ['Bombay', 'Chennai', 'Chennai', 'Delhi', 'Mysore' ], 'year' : [2001, 2005, 2003, 2001, 2000],  'pop' : [25, 35, 20, 40, 15]}
df2= pd.DataFrame(data)
print(df2)
#observe index is assigned automatically

      city  year  pop
0   Bombay  2001   25
1  Chennai  2005   35
2  Chennai  2003   20
3    Delhi  2001   40
4   Mysore  2000   15


In [14]:
# create a dataframe using a dictionary of Lists, values are lists and column names are keys
data= {'city' : ['Bombay', 'Chennai', 'Chennai', 'Delhi', 'Mysore' ], 'year' :
[2001, 2005, 2003, 2001, 2000],
 'pop' : [25, 35, 20, 40, 15]} #this will have only columns no index
labels=['a', 'b', 'c', 'd', 'e']
df2= pd.DataFrame(data, index=labels)
print(df2)
#observe index is assigned automatically

      city  year  pop
a   Bombay  2001   25
b  Chennai  2005   35
c  Chennai  2003   20
d    Delhi  2001   40
e   Mysore  2000   15


In [17]:
#14. DataFrame Attributes - index, cols, values, datatype of values

#First Create a DataFrame

data={'Animals':
['cat','cat','turtle','dog','dog','cat','turtle','cat','dog','dog'],
 'Age': [2.5,3,0.5,np.nan,5,2,4.5,np.nan,7,3],
 'Visits' : [1,3,2,3,2,3,1,1,2,1],
 'Priority' : ['y','y','n','y','n','n','n','y','n','n']}
labels=['a','b','c','d','e','f','g','h','i','j']

animals_data=pd.DataFrame(data,index=labels)
print(animals_data)
print(type(animals_data))


  Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n
<class 'pandas.core.frame.DataFrame'>


In [19]:

print("\n animals_data.index:\n ", animals_data.index)
print("\n animals_data.columns:\n", animals_data.columns)
print("\n animals_data.values:\n", animals_data.values) #will show only values without index and column names

print("\n animals_data.dtypes:\n", animals_data.dtypes) #will show the datatype of each column

#print(animals_data.head()) # will display top 5 lines of the dataFrame
#print(animals_data.tail()) # will display bottom 5 lines of the dataframe



 animals_data.index:
  Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')

 animals_data.columns:
 Index(['Animals', 'Age', 'Visits', 'Priority'], dtype='object')

 animals_data.values:
 [['cat' 2.5 1 'y']
 ['cat' 3.0 3 'y']
 ['turtle' 0.5 2 'n']
 ['dog' nan 3 'y']
 ['dog' 5.0 2 'n']
 ['cat' 2.0 3 'n']
 ['turtle' 4.5 1 'n']
 ['cat' nan 1 'y']
 ['dog' 7.0 2 'n']
 ['dog' 3.0 1 'n']]

 animals_data.dtypes:
 Animals      object
Age         float64
Visits        int64
Priority     object
dtype: object


In [25]:
#Accessing rows of a DataFrame by implict and explicit index

print("\n animals_data.loc['a', :] :\n", animals_data.loc['a', :]) #values of a row are given as columns



 animals_data.loc['a', :] :
 Animals     cat
Age         2.5
Visits        1
Priority      y
Name: a, dtype: object


In [24]:
print("\n Rows 1 to 3 using slicing: \n",animals_data.iloc[1:3, 2:3] ) #iloc for implicit indexing


 Rows 1 to 3 using slicing: 
    Visits
b       3
c       2


In [26]:
#Accessing columns of a DataFrame 2 ways
print("\n animals_data['Animals']:\n",animals_data['Animals'] )
print("\n animals_data['Age'] :\n", animals_data['Age'])
print("\n animals_data.Animal:\n",animals_data.Animals)

animals_data[['Age','Visits']] #Displaying particular Columns
print("\n animals_data.loc['b', 'Age']:\n",animals_data.loc['b', 'Age'])  #accessing by row and column

animals_data.loc['b', 'Age'] =50   #updatinng a value in a Dataframe
print("\n animals_data.loc['b', 'Age']:\n",animals_data.loc['b', 'Age']) 


 animals_data['Animals']:
 a       cat
b       cat
c    turtle
d       dog
e       dog
f       cat
g    turtle
h       cat
i       dog
j       dog
Name: Animals, dtype: object

 animals_data['Age'] :
 a    2.5
b    3.0
c    0.5
d    NaN
e    5.0
f    2.0
g    4.5
h    NaN
i    7.0
j    3.0
Name: Age, dtype: float64

 animals_data.Animal:
 a       cat
b       cat
c    turtle
d       dog
e       dog
f       cat
g    turtle
h       cat
i       dog
j       dog
Name: Animals, dtype: object

 animals_data.loc['b', 'Age']:
 3.0

 animals_data.loc['b', 'Age']:
 50.0


In [27]:
# Information about the whole dataframe
print( animals_data.info())

#nrows, ncols, index, datatype of each column, number of nonnull values
#statistical data of dataframe

print('\n Statistical Description : \n',animals_data.describe())
#mean std max min quartiles for columns with numeric type

print('\n Description for object values: \n',animals_data.describe(include =['object']))
#count, unique values, mode , freq


<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
Animals     10 non-null object
Age         8 non-null float64
Visits      10 non-null int64
Priority    10 non-null object
dtypes: float64(1), int64(1), object(2)
memory usage: 720.0+ bytes
None

 Statistical Description : 
              Age     Visits
count   8.000000  10.000000
mean    9.312500   1.900000
std    16.561439   0.875595
min     0.500000   1.000000
25%     2.375000   1.000000
50%     3.750000   2.000000
75%     5.500000   2.750000
max    50.000000   3.000000

 Description for object values: 
        Animals Priority
count       10       10
unique       3        2
top        dog        n
freq         4        6


In [28]:
print('\n Description for object values: \n',animals_data.describe(include = ['object']))



 Description for object values: 
        Animals Priority
count       10       10
unique       3        2
top        dog        n
freq         4        6


In [29]:
print("Transpose of the Data Frame :")
animals_data.T

Transpose of the Data Frame :


a    b       c    d    e    f       g    h    i    j
Animals   cat  cat  turtle  dog  dog  cat  turtle  cat  dog  dog
Age       2.5   50     0.5  NaN    5    2     4.5  NaN    7    3
Visits      1    3       2    3    2    3       1    1    2    1
Priority    y    y       n    y    n    n       n    y    n    n

In [30]:
# Operation on DataFrame
# Sorting DataFrames
# Methods in DataFrame object Sort By Values
print(animals_data)
print("\n Sorting the Data Agewise:\n", animals_data.sort_values(by = 'Age', ascending = False)) #sort by which column
#Any missing value is sorted at end by default
animals_data.sort_values(by='Age')[1:4]



  Animals   Age  Visits Priority
a     cat   2.5       1        y
b     cat  50.0       3        y
c  turtle   0.5       2        n
d     dog   NaN       3        y
e     dog   5.0       2        n
f     cat   2.0       3        n
g  turtle   4.5       1        n
h     cat   NaN       1        y
i     dog   7.0       2        n
j     dog   3.0       1        n

 Sorting the Data Agewise:
   Animals   Age  Visits Priority
b     cat  50.0       3        y
i     dog   7.0       2        n
e     dog   5.0       2        n
g  turtle   4.5       1        n
j     dog   3.0       1        n
a     cat   2.5       1        y
f     cat   2.0       3        n
c  turtle   0.5       2        n
d     dog   NaN       3        y
h     cat   NaN       1        y


Animals  Age  Visits Priority
f     cat  2.0       3        n
a     cat  2.5       1        y
j     dog  3.0       1        n

In [31]:
#Sort by index
print("\n Sorting the Data by Index:\n", animals_data.sort_index(axis=1))
#Since it is already sorted you dont see the change


 Sorting the Data by Index:
     Age Animals Priority  Visits
a   2.5     cat        y       1
b  50.0     cat        y       3
c   0.5  turtle        n       2
d   NaN     dog        y       3
e   5.0     dog        n       2
f   2.0     cat        n       3
g   4.5  turtle        n       1
h   NaN     cat        y       1
i   7.0     dog        n       2
j   3.0     dog        n       1


In [32]:
#. Create a new index Reindexing
print(animals_data)
animals_data_reindex = animals_data.reindex(['d', 'e', 'g', 'f', 'a', 'b', 'c', 'i', 'j'])

print("\n ReIndexed Data: \n",animals_data.reindex)
print("\n Sorted by row index:\n", animals_data_reindex.sort_index(axis=0))
print("\n Sorted by Column Index:\n", animals_data_reindex.sort_index(axis=1))

  Animals   Age  Visits Priority
a     cat   2.5       1        y
b     cat  50.0       3        y
c  turtle   0.5       2        n
d     dog   NaN       3        y
e     dog   5.0       2        n
f     cat   2.0       3        n
g  turtle   4.5       1        n
h     cat   NaN       1        y
i     dog   7.0       2        n
j     dog   3.0       1        n

 ReIndexed Data: 
 <bound method DataFrame.reindex of   Animals   Age  Visits Priority
a     cat   2.5       1        y
b     cat  50.0       3        y
c  turtle   0.5       2        n
d     dog   NaN       3        y
e     dog   5.0       2        n
f     cat   2.0       3        n
g  turtle   4.5       1        n
h     cat   NaN       1        y
i     dog   7.0       2        n
j     dog   3.0       1        n>

 Sorted by row index:
   Animals   Age  Visits Priority
a     cat   2.5       1        y
b     cat  50.0       3        y
c  turtle   0.5       2        n
d     dog   NaN       3        y
e     dog   5.0       2      

In [35]:
#23. Creating a copy
animals_data_c=animals_data.copy()
print("\n Copy of animals_data:\n", animals_data_c)


 Copy of animals_data:
   Animals   Age  Visits Priority
a     cat   2.5       1        y
b     cat  50.0       3        y
c  turtle   0.5       2        n
d     dog   NaN       3        y
e     dog   5.0       2        n
f     cat   2.0       3        n
g  turtle   4.5       1        n
h     cat   NaN       1        y
i     dog   7.0       2        n
j     dog   3.0       1        n


In [36]:
#24. Deleting a row or Column of a DataFrame
print(animals_data)
print("Drop rows with names 'a; and 'b':\n", animals_data.drop(['a', 'b']))

#dropping rows
#to drop the columns permanently use inplace - True

print("Drop rows with names 'a; and 'b':\n", animals_data_c.drop(['a', 'b'], inplace=True))

#print(animals_data.drop('Visits', axis=1))

#dropping column columns are axis=1 for drop() default is row
#So if we dont mention axis = 1 it will search for a row with name 'Visits'

#print(animals_data.drop('Visits', axis='columns'))


  Animals   Age  Visits Priority
a     cat   2.5       1        y
b     cat  50.0       3        y
c  turtle   0.5       2        n
d     dog   NaN       3        y
e     dog   5.0       2        n
f     cat   2.0       3        n
g  turtle   4.5       1        n
h     cat   NaN       1        y
i     dog   7.0       2        n
j     dog   3.0       1        n
Drop rows with names 'a; and 'b':
   Animals  Age  Visits Priority
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n
Drop rows with names 'a; and 'b':
 None


In [37]:
#Why doing an Aggregation on a Row doesnt make sense
print("Mean of the Dataframe is: \n",animals_data.mean()) #mean of values in columns containing numeric data
print("\nMean of 'Age' is: ",animals_data[['Age']].mean())
print("\nTotal visits :",animals_data[['Visits']].sum())
print("\nMax visits: ",animals_data[['Visits']].max())
print("\nMin visits: ",animals_data[['Visits']].min())
print("\n Index of Max visits: ",animals_data[['Visits']].idxmax())
print("\n Index of Min visits: ",animals_data[['Visits']].idxmin())
print("\nSum: \n",animals_data.sum()) #for strings sum is string concatenation

Mean of the Dataframe is: 
 Age       9.3125
Visits    1.9000
dtype: float64

Mean of 'Age' is:  Age    9.3125
dtype: float64

Total visits : Visits    19
dtype: int64

Max visits:  Visits    3
dtype: int64

Min visits:  Visits    1
dtype: int64

 Index of Max visits:  Visits    b
dtype: object

 Index of Min visits:  Visits    a
dtype: object

Sum: 
 Animals     catcatturtledogdogcatturtlecatdogdog
Age                                         74.5
Visits                                        19
Priority                              yynynnnynn
dtype: object
